% % % open all the files 
% aFiles = {{'G:\PhD\Experiments\Auckland\InSituPrep\20130222\121833Pressure.mat', ...
%     'G:\PhD\Experiments\Auckland\InSituPrep\20130222\123610Pressure.mat'}, ...
%     {'G:\PhD\Experiments\Auckland\InSituPrep\20130619\140722Pressure.mat'}, ...
%     {'G:\PhD\Experiments\Auckland\InSituPrep\20130620\150803Pressure.mat'}, ...
%     {'G:\PhD\Experiments\Auckland\InSituPrep\20130724\115754Pressure.mat'}, ...
%     {'G:\PhD\Experiments\Auckland\InSituPrep\20130815\124736Pressure.mat', ...
%     'G:\PhD\Experiments\Auckland\InSituPrep\20130815\130618Pressure.mat'}, ...
%     {'G:\PhD\Experiments\Auckland\InSituPrep\20140415\162851Pressure.mat', ...
%     'G:\PhD\Experiments\Auckland\InSituPrep\20140415\164858Pressure.mat'}, ...
%     {'G:\PhD\Experiments\Auckland\InSituPrep\20140417\124544Pressure.mat', ...
%     'G:\PhD\Experiments\Auckland\InSituPrep\20140417\130600Pressure.mat'}, ...
%     {'G:\PhD\Experiments\Auckland\InSituPrep\20140430\184650Pressure.mat', ...
%     'G:\PhD\Experiments\Auckland\InSituPrep\20140430\190541Pressure.mat'}, ...
%     {'G:\PhD\Experiments\Auckland\InSituPrep\20140501\171122Pressure.mat', ...
%     'G:\PhD\Experiments\Auckland\InSituPrep\20140501\173129Pressure.mat'}, ...
%     {'G:\PhD\Experiments\Auckland\InSituPrep\20140505\145234Pressure.mat', ...
%     'G:\PhD\Experiments\Auckland\InSituPrep\20140505\151242Pressure.mat'}, ...
%     {'G:\PhD\Experiments\Auckland\InSituPrep\20140507\132514Pressure.mat', ...
%     'G:\PhD\Experiments\Auckland\InSituPrep\20140507\135024Pressure.mat'} ...
%     };
% 
% aPressureData = cell(numel(aFiles),1);
% for i = 1:numel(aPressureData)
%     aThisFile = aFiles{i};
%     aCellArray = cell(numel(aThisFile),1);
%     for j = 1:numel(aThisFile)
%         aCellArray{j} = GetPressureFromMATFile(Pressure,char(aThisFile{j}),'Extracellular');
%         fprintf('Got file %s\n',char(aThisFile{j}));
%     end
%     aPressureData{i} = aCellArray;
% end

% aPhrenicStartDurations = cell(numel(aPressureData),1);
% aPhrenicEndDurations = cell(numel(aPressureData),1);
% for i = 1:numel(aPhrenicStartDurations)
%     if numel(aPressureData{i}) > 1
%         aPhrenicStartDurations{i} = aPressureData{i}{1}.oPhrenic.Electrodes.Processed.BurstDurations;
%         aPhrenicEndDurations{i} = aPressureData{i}{2}.oPhrenic.Electrodes.Processed.BurstDurations;
%     end
% end
% 
% aPhrenicFirstDurations = [aPhrenicStartDurations{1} ; aPhrenicStartDurations{5} ; aPhrenicStartDurations{6}; ...
%     aPhrenicStartDurations{7}; aPhrenicStartDurations{8}; aPhrenicStartDurations{9}; ...
%     aPhrenicStartDurations{10}; aPhrenicStartDurations{11}];
% aPhrenicSecondDurations = [aPhrenicEndDurations{1} ; aPhrenicEndDurations{5} ; aPhrenicEndDurations{6}; ...
%     aPhrenicEndDurations{7}; aPhrenicEndDurations{8}; aPhrenicEndDurations{9}; ...
%     aPhrenicEndDurations{10}; aPhrenicEndDurations{11}];
% fprintf('Mean Phrenic Duration decreased from %3.2f +/- %3.2f to %3.2f +/- %3.2f\n',mean(aPhrenicFirstDurations),...
%     std(aPhrenicFirstDurations)/sqrt(numel(aPhrenicFirstDurations)),...
%     mean(aPhrenicSecondDurations),...
%     std(aPhrenicSecondDurations)/sqrt(numel(aPhrenicSecondDurations)));
% 
% figure();
% bplot(aPhrenicFirstDurations,1);
% hold on;
% bplot(aPhrenicSecondDurations,2,'nolegend');
% hold off;
% oAxes = gca;
% set(oAxes,'xlim',[0.5 2.5]);
% set(oAxes,'xticklabel',{'','Durations at Start','','20 min later',''});
% set(get(oAxes,'ylabel'),'string','Duration of Phrenic Burst (s)');
% 
% aPhrenicStartRates = cell(numel(aPressureData),1);
% aPhrenicEndRates = cell(numel(aPressureData),1);
% for i = 1:numel(aPhrenicStartRates)
%     if numel(aPressureData{i}) > 1
%         aPhrenicStartRates{i} = aPressureData{i}{1}.oPhrenic.Electrodes.Processed.BurstRates;
%         aPhrenicEndRates{i} = aPressureData{i}{2}.oPhrenic.Electrodes.Processed.BurstRates;
%     end
% end
% 
% aPhrenicFirstRates = [aPhrenicStartRates{1} , aPhrenicStartRates{5} , aPhrenicStartRates{6}, ...
%     aPhrenicStartRates{7}, aPhrenicStartRates{8}, aPhrenicStartRates{9}, ...
%     aPhrenicStartRates{10}, aPhrenicStartRates{11}];
% aPhrenicSecondRates = [aPhrenicEndRates{1} , aPhrenicEndRates{5} , aPhrenicEndRates{6}, ...
%     aPhrenicEndRates{7}, aPhrenicEndRates{8}, aPhrenicEndRates{9}, ...
%     aPhrenicEndRates{10}, aPhrenicEndRates{11}];
% fprintf('Mean Phrenic Rate Increased from %3.2f +/- %3.2f to %3.2f +/- %3.2f\n',mean(aPhrenicFirstRates),...
%     std(aPhrenicFirstRates)/sqrt(numel(aPhrenicFirstRates)),...
%     mean(aPhrenicSecondRates),...
%     std(aPhrenicSecondRates)/sqrt(numel(aPhrenicSecondRates)));
% 
% figure();
% bplot(aPhrenicFirstRates,1);
% hold on;
% bplot(aPhrenicSecondRates,2,'nolegend');
% hold off;
% oAxes = gca;
% set(oAxes,'xlim',[0.5 2.5]);
% set(oAxes,'xticklabel',{'','At Start','','20 min later',''});
% set(get(oAxes,'ylabel'),'string','Phrenic Burst Rate (bpm)');

aSecondPressure = zeros(numel(aPressureData),1);
for i = 1:numel(aSecondPressure)
    if numel(aPressureData{i}) > 1
        aSecondPressure(i) = mean(aPressureData{i}{2}.Processed.Data);
    end
end
aSecondPressure = aSecondPressure(aSecondPressure>0);
fprintf('Mean baseline pressure %3.2f +/- %3.2f\n',mean(aSecondPressure),std(aSecondPressure)/sqrt(numel(aSecondPressure)));